replicaCount: 1

mysql:
  name: wordpress-mysql
  port: 3306
  labels:
      app: wordpress
      tier: mysql
  env:
    name: MYSQL_ROOT_PASSWORD
    secretKey: mysql-pass-bc6ggk5g2t 
    key: password
  deployment:
    image: mysql:5.6
    volumes:
      name: mysql-persistent-storage
      mountPath: /var/lib/mysql
      claimName: mysql-pv-claim
  pvc:
    name: mysql-pv-claim
    storage: 20Gi
wordpress:
  


