---
replicaCount: 1

app: wordpress
mysql:
  name: wordpress-mysql
  port: 3306
  tier: mysql 
  env:
    name: MYSQL_ROOT_PASSWORD
    secretKey: mysql-pass-bc6ggk5g2t 
    key: password
  deployment:
    image: mysql:5.6
    volumes:
      name: mysql-persistent-storage
      mountPath: /var/lib/mysql
  pvc:
    name: mysql-pv-claim
    storage: 20Gi
wordpress:
  port: 80
  tier: frontend
  env:
    name: WORDPRESS_DB_HOST
    value: wordpress-mysql
    passName: WORDPRESS_DB_PASSWORD
  deployment:
    image: wordpress:4.8-apache
    volumes:
      name: wordpress-persistent-storage
      mountPath: /var/www/html
  pvc:
    name: wp-pv-claim
    storage: 20Gi

kube-prometheus-stack:
  prometheus-node-exporter:
    hostRootFsMount: 
      enabled:  false

prometheus-mysql-exporter:
  mysql:
    user: root
    pass: password
    host: localhost
    port: 3306
  serviceMonitor:
    enabled: enabled
  serviceAccount:
    create: true
