apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}
  labels:
    app: {{ .Values.mysql.labels.app }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mysql.labels.app }}
      tier: {{ .Values.mysql.labels.tier }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.labels.app }}
        tier: {{ .Values.mysql.labels.tier }}
    spec:
      containers:
      - image: {{ .Values.mysql.deployment.image }}
        name: {{ .Values.mysql.labels.tier }}
        env:
        - name: {{ .Values.mysql.env.name }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql.env.secretKey }} 
              key: {{ .Values.mysql.env.key }}
        ports:
        - containerPort: {{ .Values.mysql.port }}
          name: {{ .Values.mysql.labels.tier }}
        volumeMounts:
        - name: {{ .Values.mysql.deployment.volumes.name }}
          mountPath: {{ .Values.mysql.deployment.volumes.mountPath }}
      volumes:
      - name: {{ .Values.mysql.deployment.volumes.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.mysql.deployment.volumes.claimName }}
