apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
  labels:
    app: {{ .Values.mysql.labels.app }}
spec:
  ports:
    - port: {{ .Values.mysql.port }}
  selector:
    app: {{ .Values.mysql.labels.app }}
    tier: {{ .Values.mysql.labels.tier }}
  clusterIP: None

