---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app}}
  labels:
    app: {{.Values.app}}
spec:
  ports:
    - port: {{.Values.wordpress.port}}
  selector:
    app: {{.Values.app }}
    tier: {{.Values.wordpress.tier}}
  type: LoadBalancer
