---
name: Test files

on: [push]

jobs:
  yamllint:
    runs-on: ubuntu-latest
    container: ghcr.io/olivercutting/wordpresscluster:main
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - run: |
        yamllint .

  helm-lint:
    runs-on: ubuntu-latest
    container: ghcr.io/olivercutting/wordpresscluster:main
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - run: |
        helm lint wordpress
  
  kics:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: KICS Github Action
      uses: Checkmarx/kics-github-action@v1.5
      with:
        path: .
